name: Nightly Jobs
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  run-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Snapshot Daily
        run: echo "Enable later: POST https://api.example.tld/api/jobs/snapshot-daily"
      - name: Retention
        run: echo "Enable later: POST https://api.example.tld/api/jobs/retention"
