name: PR Checks

on:
  pull_request:
    branches: [ main, production ]
    paths:
      - 'apps/web/**'
      - 'apps/api/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read

concurrency:
  group: pr-checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-checks:
    name: Web App Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: TypeScript type check
        run: npm run typecheck
      
      - name: ESLint check
        run: npm run lint
      
      - name: Prettier format check
        run: npm run format:check
      
      - name: Build check
        run: npm run build
      
      - name: Test build artifacts
        run: |
          if [ -d ".next" ]; then
            echo "✅ Build artifacts created successfully"
            ls -la .next/
          else
            echo "❌ Build artifacts not found"
            exit 1
          fi

  api-checks:
    name: API Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Ruff linting
        run: ruff check .
      
      - name: Ruff formatting check
        run: ruff format --check .
      
      - name: Type checking (if mypy is available)
        run: |
          if command -v mypy &> /dev/null; then
            mypy .
          else
            echo "⚠️ mypy not available, skipping type check"
          fi
        continue-on-error: true

  build-validation:
    name: Build Validation
    runs-on: ubuntu-latest
    needs: [web-checks, api-checks]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate web build
        working-directory: apps/web
        run: |
          # Setup Node.js for build validation
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          
          # Install dependencies and build
          npm ci
          npm run build
          
          # Validate build output
          if [ -d ".next" ]; then
            echo "✅ Web build validation passed"
          else
            echo "❌ Web build validation failed"
            exit 1
          fi
      
      - name: Validate API structure
        working-directory: apps/api
        run: |
          # Setup Python for API validation
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs python3 python3-pip
          
          # Install dependencies
          pip3 install -r requirements.txt
          
          # Validate API can start (dry run)
          python3 -c "import app; print('✅ API structure validation passed')"
