# fly.toml app configuration file generated for online-table-lite-api on 2025-09-02T15:47:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'online-table-lite-api'
primary_region = 'fra'

[build]

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
