name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - preview

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    
    environment: 
      name: ${{ github.event.inputs.environment }}
    
    steps:
      - uses: actions/checkout@v4
      
      # Deploy Web App
      - name: Deploy Web App
        working-directory: apps/web
        run: |
          # Setup Node.js
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          
          # Install dependencies and build
          npm ci
          npm run build
          
          # Install Vercel CLI and deploy
          npm install --global vercel@latest
          vercel pull --yes --environment=${{ github.event.inputs.environment }} --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      
      # Deploy API
      - name: Deploy API
        working-directory: apps/api
        run: |
          # Install Flyctl
          curl -L https://fly.io/install.sh | sh
          export PATH="$PATH:$HOME/.fly/bin"
          
          # Deploy
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
      - name: Deployment Complete
        run: |
          echo "🚀 Deployment to ${{ github.event.inputs.environment }} completed!"
          echo "✅ Web app and API are now live"
