name: Deploy API (Fly.io)
on:
  push:
    branches: [ production ]
    paths:
      - 'apps/api/**'
      - '.github/workflows/deploy-api.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy
        working-directory: apps/api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
